# Generated by Django 6.0.6 on 2026-06-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aerolinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("destino", models.CharField(max_length=100, unique=True)),
                ("duracion_minutos", models.TimeField(blank=True, null=True)),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "Aerolinea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vuelos",
                        to="skyport.aerolinea",
                    ),
                ),
            ],
        ),
    ]
